In [2]:
import sys
sys.path.append("../")
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder as SklearnOneHotEncoder
from sklearn.datasets import load_iris
from preprocessing.OneHotEncoder import OneHotEncoder  # Adjust import path as needed

def test_one_hot_encoder():
    data = load_iris()
    X = data.data
    y = data.target.reshape(-1, 1)  # Make y a 2D array for the encoders

    # Combine X and y for complete one-hot encoding on dataset features including target
    X = np.hstack([X, y])

    # Custom OneHotEncoder
    custom_encoder = OneHotEncoder()
    X_custom_encoded = custom_encoder.fit_transform(X)

    # Sklearn OneHotEncoder
    sklearn_encoder = SklearnOneHotEncoder(sparse_output=False)
    X_sklearn_encoded = sklearn_encoder.fit_transform(X)

    # Output comparison
    assert np.array_equal(X_custom_encoded, X_sklearn_encoded), "Mismatch in one-hot encoded results"
    print(X_custom_encoded)
    print("Custom OneHotEncoder tests passed successfully!")
    print("One-hot encoded data shape:", X_custom_encoded.shape)

test_one_hot_encoder()


[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]
Custom OneHotEncoder tests passed successfully!
One-hot encoded data shape: (150, 126)
