In [2]:
from sklearn.datasets import load_iris
from preprocessing.MinMaxScaler import MinMaxScaler
import numpy as np

# Load the Iris dataset
data = load_iris()
X, y = data.data, data.target

# Apply MinMaxScaler
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Display the results
print("Original Data:\n", X[:5])
print("\nScaled Data:\n", X_scaled[:5])

# Check if the scaled data is in the range [0, 1]
assert np.all(X_scaled >= 0) and np.all(X_scaled <= 1), "Data is not properly scaled to the range [0, 1]"

print("Iris dataset successfully scaled to [0, 1] using MinMaxScaler.")

Original Data:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Scaled Data:
 [[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]]
Iris dataset successfully scaled to [0, 1] using MinMaxScaler.
