In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler as SklearnMinMaxScaler
from sklearn.datasets import load_iris
from preprocessing.MinMaxScaler import MinMaxScaler  # Adjust import path as needed

def test_minmax_scaler():
    data = load_iris()
    X = data.data

    # Custom MinMaxScaler
    custom_scaler = MinMaxScaler()
    X_custom_scaled = custom_scaler.fit_transform(X)

    # Sklearn MinMaxScaler
    sklearn_scaler = SklearnMinMaxScaler()
    X_sklearn_scaled = sklearn_scaler.fit_transform(X)

    # Output comparison
    print("Custom MinMax Scaled Data:\n", X_custom_scaled[:5])
    print("Sklearn MinMax Scaled Data:\n", X_sklearn_scaled[:5])

    # Assert close
    assert np.allclose(X_custom_scaled, X_sklearn_scaled), "Mismatch in MinMaxScaler results"

    print("MinMaxScaler test passed!")

test_minmax_scaler()


Custom MinMax Scaled Data:
 [[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]]
Sklearn MinMax Scaled Data:
 [[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]]
MinMaxScaler test passed!
